#!/bin/bash

# Runpaymentcycle: run all components (payment calculator, sender, reporter)
# or just some of them.

# Config section: adapt to your own needs.
# ----------------------------------------

# If you have Python3 virtual environment set up, point here to its 'activate'
# file. If you don't have a venv, then all modules etc. must be available to
# the global Python.
VENV_ACTIVATE="/home/ark/PayoutScriptArk/ark/bin/activate"

# How to invoke your Python. It must be version 3. Usually the default below
# is ok.
PYTHON3="python3"

# End of configuration. You should not alter anything below here.
# ---------------------------------------------------------------

# Print usage and die
usage() {
    cat <<EOF 1>&2
This is runpaymentcycle, the control script for all subparts.
Usage:
  runpaymentcycle calculator
    Computes payments and stores them in separate files in directory
    PAYOUTDIR (see config.py)
  runpaymentcycle sender
    Picks up prepared payment files and sends payment instructions. Files that
    fail to process are moved to PAYOUTFAILDIR
  runpaymentcycle both
    Runs both of the above (calculator and sender)
  runpaymentcycle reporter
    Reports on the generic state
  runpaymentcycle all
    Runs all of the above (calculator, sender and reporter)
  runpaymentcycle displayer FILE(s)
    Displays contents of the payment files, used for debugging failures.
EOF
    exit 1
}

# Test arguments: what should we run.
[ -z "$1" ] && usage
run_calculator=0
run_sender=0
run_reporter=0
run_displayer=0
case "$1" in
    calculator)
	run_calculator=1
	;;
    sender)
	run_sender=1
	;;
    reporter)
	run_reporter=1
	;;
    displayer)
	run_displayer=1
	;;
    both)
	run_calculator=1
	run_sender=1
    all)
	run_calculator=1
	run_sender=1
	run_reporter=1
	;;
    *)
	usage
    esac

# Source the virtual env if applicable
if [ -n "${VENV_ACTIVATE}" ] ; then
    source "${VENV_ACTIVATE}" || exit 1
fi

# Determine the base dir of this script. The Python scripts are expected
# right next to it.
dir=$(dirname $0)

# Run the parts.
if [ "${run_calculator}" -eq 1 ] ; then
    "${PYTHON3}" "${dir}/payoutcalculator.py" || exit 1
fi

if [ "${run_sender}" -eq 1 ] ; then
    "${PYTHON3}" "${dir}/payoutsender.py" || exit 1
fi

if [ "${run_reporter}" -eq 1 ] ; then
    "${PYTHON3}" "${dir}/payoutreporter.py" || exit 1
fi
    
if [ "${run_displayer}" -eq 1 ] ; then
    shift
    "${PYTHON3}" "${dir}/payoutdisplayer.py" "$@" || exit 1
fi
    

